import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Evernote.module.scss'
import NoteDetails from './components/NoteDetails';
import NoteOperation from './components/NoteOperation';


export default function Home() {
  const [ID, setID] =useState(null)
  const [id, setId] = useState(null);
 
  
  const getSingleNote = (id) => {
      setID(id)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app"  key="title"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          <div className={styles.left} >
           {/* <NoteOperation getSingleNote={getSingleNote}/> */}
           <NoteOperation getSingleNote={getSingleNote} />
          </div>
          <div>
            <NoteDetails ID={ID} />
          </div>

        </div>
      </main>

     
    </div>
  )
}
